import { CategoryMap } from './types';

export const INITIAL_DATA: CategoryMap = {
  Pharmacy: {
    'Pain Relief': [
      { id: 'P-001', name: 'Paracetamol 500mg', category: 'Pharmacy', subCategory: 'Pain Relief', price: 25, quantity: 120 },
      { id: 'P-002', name: 'Ibuprofen 200mg', category: 'Pharmacy', subCategory: 'Pain Relief', price: 32, quantity: 80 },
      { id: 'P-003', name: 'Aspirin 100mg', category: 'Pharmacy', subCategory: 'Pain Relief', price: 18, quantity: 95 },
      { id: 'P-004', name: 'Diclofenac 50mg', category: 'Pharmacy', subCategory: 'Pain Relief', price: 45, quantity: 60 },
      { id: 'P-005', name: 'Naproxen 250mg', category: 'Pharmacy', subCategory: 'Pain Relief', price: 38, quantity: 45 },
      { id: 'P-006', name: 'Tramadol 50mg', category: 'Pharmacy', subCategory: 'Pain Relief', price: 120, quantity: 25 },
      { id: 'P-007', name: 'Codeine 30mg', category: 'Pharmacy', subCategory: 'Pain Relief', price: 85, quantity: 30 },
      { id: 'P-008', name: 'Morphine 10mg', category: 'Pharmacy', subCategory: 'Pain Relief', price: 200, quantity: 15 },
    ],
    Antibiotics: [
      { id: 'P-101', name: 'Amoxicillin 500mg', category: 'Pharmacy', subCategory: 'Antibiotics', price: 84, quantity: 40 },
      { id: 'P-102', name: 'Azithromycin 250mg', category: 'Pharmacy', subCategory: 'Antibiotics', price: 95, quantity: 35 },
      { id: 'P-103', name: 'Ciprofloxacin 500mg', category: 'Pharmacy', subCategory: 'Antibiotics', price: 110, quantity: 28 },
      { id: 'P-104', name: 'Doxycycline 100mg', category: 'Pharmacy', subCategory: 'Antibiotics', price: 75, quantity: 42 },
      { id: 'P-105', name: 'Metronidazole 400mg', category: 'Pharmacy', subCategory: 'Antibiotics', price: 65, quantity: 38 },
      { id: 'P-106', name: 'Cephalexin 500mg', category: 'Pharmacy', subCategory: 'Antibiotics', price: 88, quantity: 33 },
      { id: 'P-107', name: 'Clarithromycin 250mg', category: 'Pharmacy', subCategory: 'Antibiotics', price: 125, quantity: 25 },
      { id: 'P-108', name: 'Levofloxacin 500mg', category: 'Pharmacy', subCategory: 'Antibiotics', price: 140, quantity: 20 },
    ],
    Vitamins: [
      { id: 'P-201', name: 'Vitamin C 1000mg', category: 'Pharmacy', subCategory: 'Vitamins', price: 59, quantity: 65 },
      { id: 'P-202', name: 'Vitamin D3 1000IU', category: 'Pharmacy', subCategory: 'Vitamins', price: 45, quantity: 80 },
      { id: 'P-203', name: 'Vitamin B12 1000mcg', category: 'Pharmacy', subCategory: 'Vitamins', price: 38, quantity: 90 },
      { id: 'P-204', name: 'Multivitamin Complex', category: 'Pharmacy', subCategory: 'Vitamins', price: 75, quantity: 55 },
      { id: 'P-205', name: 'Omega-3 Fish Oil', category: 'Pharmacy', subCategory: 'Vitamins', price: 95, quantity: 40 },
      { id: 'P-206', name: 'Calcium + D3', category: 'Pharmacy', subCategory: 'Vitamins', price: 65, quantity: 70 },
      { id: 'P-207', name: 'Iron + Folic Acid', category: 'Pharmacy', subCategory: 'Vitamins', price: 42, quantity: 85 },
      { id: 'P-208', name: 'Zinc 50mg', category: 'Pharmacy', subCategory: 'Vitamins', price: 28, quantity: 100 },
    ],
    Diabetes: [
      { id: 'P-301', name: 'Metformin 500mg', category: 'Pharmacy', subCategory: 'Diabetes', price: 55, quantity: 75 },
      { id: 'P-302', name: 'Gliclazide 80mg', category: 'Pharmacy', subCategory: 'Diabetes', price: 68, quantity: 60 },
      { id: 'P-303', name: 'Glimepiride 1mg', category: 'Pharmacy', subCategory: 'Diabetes', price: 72, quantity: 55 },
      { id: 'P-304', name: 'Sitagliptin 100mg', category: 'Pharmacy', subCategory: 'Diabetes', price: 180, quantity: 30 },
      { id: 'P-305', name: 'Insulin Regular', category: 'Pharmacy', subCategory: 'Diabetes', price: 450, quantity: 25 },
      { id: 'P-306', name: 'Insulin NPH', category: 'Pharmacy', subCategory: 'Diabetes', price: 380, quantity: 28 },
    ],
    Cardiovascular: [
      { id: 'P-401', name: 'Amlodipine 5mg', category: 'Pharmacy', subCategory: 'Cardiovascular', price: 42, quantity: 88 },
      { id: 'P-402', name: 'Lisinopril 10mg', category: 'Pharmacy', subCategory: 'Cardiovascular', price: 58, quantity: 65 },
      { id: 'P-403', name: 'Atenolol 50mg', category: 'Pharmacy', subCategory: 'Cardiovascular', price: 35, quantity: 95 },
      { id: 'P-404', name: 'Simvastatin 20mg', category: 'Pharmacy', subCategory: 'Cardiovascular', price: 68, quantity: 70 },
      { id: 'P-405', name: 'Losartan 50mg', category: 'Pharmacy', subCategory: 'Cardiovascular', price: 75, quantity: 58 },
      { id: 'P-406', name: 'Hydrochlorothiazide 25mg', category: 'Pharmacy', subCategory: 'Cardiovascular', price: 28, quantity: 110 },
    ],
  },
  Grocery: {
    Beverages: [
      { id: 'G-001', name: 'Orange Juice 1L', category: 'Grocery', subCategory: 'Beverages', price: 21, quantity: 30 },
      { id: 'G-002', name: 'Green Tea 50pcs', category: 'Grocery', subCategory: 'Beverages', price: 18, quantity: 55 },
      { id: 'G-003', name: 'Coffee Beans 500g', category: 'Grocery', subCategory: 'Beverages', price: 45, quantity: 40 },
      { id: 'G-004', name: 'Black Tea 100pcs', category: 'Grocery', subCategory: 'Beverages', price: 22, quantity: 65 },
      { id: 'G-005', name: 'Apple Juice 1L', category: 'Grocery', subCategory: 'Beverages', price: 24, quantity: 35 },
      { id: 'G-006', name: 'Coconut Water 330ml', category: 'Grocery', subCategory: 'Beverages', price: 35, quantity: 50 },
      { id: 'G-007', name: 'Energy Drink 250ml', category: 'Grocery', subCategory: 'Beverages', price: 28, quantity: 80 },
      { id: 'G-008', name: 'Lemonade 1L', category: 'Grocery', subCategory: 'Beverages', price: 19, quantity: 45 },
    ],
    Snacks: [
      { id: 'G-101', name: 'Potato Chips 150g', category: 'Grocery', subCategory: 'Snacks', price: 12, quantity: 200 },
      { id: 'G-102', name: 'Popcorn 100g', category: 'Grocery', subCategory: 'Snacks', price: 8, quantity: 150 },
      { id: 'G-103', name: 'Mixed Nuts 200g', category: 'Grocery', subCategory: 'Snacks', price: 35, quantity: 75 },
      { id: 'G-104', name: 'Chocolate Bar 100g', category: 'Grocery', subCategory: 'Snacks', price: 15, quantity: 120 },
      { id: 'G-105', name: 'Cookies 250g', category: 'Grocery', subCategory: 'Snacks', price: 18, quantity: 90 },
      { id: 'G-106', name: 'Pretzels 150g', category: 'Grocery', subCategory: 'Snacks', price: 10, quantity: 110 },
      { id: 'G-107', name: 'Trail Mix 300g', category: 'Grocery', subCategory: 'Snacks', price: 42, quantity: 60 },
      { id: 'G-108', name: 'Granola Bars 6pcs', category: 'Grocery', subCategory: 'Snacks', price: 25, quantity: 85 },
    ],
    Dairy: [
      { id: 'G-201', name: 'Whole Milk 1L', category: 'Grocery', subCategory: 'Dairy', price: 15, quantity: 90 },
      { id: 'G-202', name: 'Yogurt 500g', category: 'Grocery', subCategory: 'Dairy', price: 22, quantity: 70 },
      { id: 'G-203', name: 'Cheese 200g', category: 'Grocery', subCategory: 'Dairy', price: 45, quantity: 55 },
      { id: 'G-204', name: 'Butter 250g', category: 'Grocery', subCategory: 'Dairy', price: 38, quantity: 65 },
      { id: 'G-205', name: 'Cream 200ml', category: 'Grocery', subCategory: 'Dairy', price: 28, quantity: 80 },
      { id: 'G-206', name: 'Cottage Cheese 300g', category: 'Grocery', subCategory: 'Dairy', price: 32, quantity: 45 },
      { id: 'G-207', name: 'Sour Cream 250g', category: 'Grocery', subCategory: 'Dairy', price: 25, quantity: 60 },
      { id: 'G-208', name: 'Ice Cream 1L', category: 'Grocery', subCategory: 'Dairy', price: 55, quantity: 35 },
    ],
    Fruits: [
      { id: 'G-301', name: 'Apples 1kg', category: 'Grocery', subCategory: 'Fruits', price: 45, quantity: 40 },
      { id: 'G-302', name: 'Bananas 1kg', category: 'Grocery', subCategory: 'Fruits', price: 28, quantity: 60 },
      { id: 'G-303', name: 'Oranges 1kg', category: 'Grocery', subCategory: 'Fruits', price: 35, quantity: 50 },
      { id: 'G-304', name: 'Grapes 500g', category: 'Grocery', subCategory: 'Fruits', price: 42, quantity: 45 },
      { id: 'G-305', name: 'Strawberries 250g', category: 'Grocery', subCategory: 'Fruits', price: 38, quantity: 35 },
      { id: 'G-306', name: 'Mangoes 1kg', category: 'Grocery', subCategory: 'Fruits', price: 55, quantity: 30 },
      { id: 'G-307', name: 'Pineapples 1kg', category: 'Grocery', subCategory: 'Fruits', price: 48, quantity: 25 },
      { id: 'G-308', name: 'Watermelons 3kg', category: 'Grocery', subCategory: 'Fruits', price: 65, quantity: 20 },
    ],
    Vegetables: [
      { id: 'G-401', name: 'Tomatoes 1kg', category: 'Grocery', subCategory: 'Vegetables', price: 32, quantity: 55 },
      { id: 'G-402', name: 'Onions 1kg', category: 'Grocery', subCategory: 'Vegetables', price: 25, quantity: 70 },
      { id: 'G-403', name: 'Potatoes 2kg', category: 'Grocery', subCategory: 'Vegetables', price: 28, quantity: 65 },
      { id: 'G-404', name: 'Carrots 1kg', category: 'Grocery', subCategory: 'Vegetables', price: 22, quantity: 60 },
      { id: 'G-405', name: 'Broccoli 500g', category: 'Grocery', subCategory: 'Vegetables', price: 35, quantity: 40 },
      { id: 'G-406', name: 'Spinach 250g', category: 'Grocery', subCategory: 'Vegetables', price: 18, quantity: 75 },
      { id: 'G-407', name: 'Bell Peppers 500g', category: 'Grocery', subCategory: 'Vegetables', price: 42, quantity: 45 },
      { id: 'G-408', name: 'Cucumbers 500g', category: 'Grocery', subCategory: 'Vegetables', price: 20, quantity: 80 },
    ],
    Grains: [
      { id: 'G-501', name: 'White Rice 5kg', category: 'Grocery', subCategory: 'Grains', price: 85, quantity: 25 },
      { id: 'G-502', name: 'Brown Rice 2kg', category: 'Grocery', subCategory: 'Grains', price: 65, quantity: 35 },
      { id: 'G-503', name: 'Whole Wheat Bread', category: 'Grocery', subCategory: 'Grains', price: 15, quantity: 90 },
      { id: 'G-504', name: 'Pasta 500g', category: 'Grocery', subCategory: 'Grains', price: 18, quantity: 85 },
      { id: 'G-505', name: 'Oats 1kg', category: 'Grocery', subCategory: 'Grains', price: 45, quantity: 50 },
      { id: 'G-506', name: 'Quinoa 500g', category: 'Grocery', subCategory: 'Grains', price: 95, quantity: 30 },
      { id: 'G-507', name: 'Barley 1kg', category: 'Grocery', subCategory: 'Grains', price: 38, quantity: 55 },
      { id: 'G-508', name: 'Buckwheat 500g', category: 'Grocery', subCategory: 'Grains', price: 52, quantity: 40 },
    ],
  },
  Electronics: {
    Smartphones: [
      { id: 'E-001', name: 'iPhone 15 Pro 128GB', category: 'Electronics', subCategory: 'Smartphones', price: 89999, quantity: 15 },
      { id: 'E-002', name: 'Samsung Galaxy S24 128GB', category: 'Electronics', subCategory: 'Smartphones', price: 74999, quantity: 20 },
      { id: 'E-003', name: 'Google Pixel 8 128GB', category: 'Electronics', subCategory: 'Smartphones', price: 64999, quantity: 18 },
      { id: 'E-004', name: 'OnePlus 12 256GB', category: 'Electronics', subCategory: 'Smartphones', price: 59999, quantity: 25 },
      { id: 'E-005', name: 'Xiaomi 14 256GB', category: 'Electronics', subCategory: 'Smartphones', price: 54999, quantity: 22 },
    ],
    Laptops: [
      { id: 'E-101', name: 'MacBook Air M2 13" 256GB', category: 'Electronics', subCategory: 'Laptops', price: 99999, quantity: 12 },
      { id: 'E-102', name: 'Dell XPS 13 512GB', category: 'Electronics', subCategory: 'Laptops', price: 89999, quantity: 15 },
      { id: 'E-103', name: 'HP Spectre x360 1TB', category: 'Electronics', subCategory: 'Laptops', price: 79999, quantity: 18 },
      { id: 'E-104', name: 'Lenovo ThinkPad X1 512GB', category: 'Electronics', subCategory: 'Laptops', price: 84999, quantity: 14 },
      { id: 'E-105', name: 'ASUS ROG Zephyrus 1TB', category: 'Electronics', subCategory: 'Laptops', price: 129999, quantity: 8 },
    ],
    Accessories: [
      { id: 'E-201', name: 'AirPods Pro 2nd Gen', category: 'Electronics', subCategory: 'Accessories', price: 24999, quantity: 45 },
      { id: 'E-202', name: 'Samsung Galaxy Buds2 Pro', category: 'Electronics', subCategory: 'Accessories', price: 19999, quantity: 50 },
      { id: 'E-203', name: 'Apple Watch Series 9 45mm', category: 'Electronics', subCategory: 'Accessories', price: 39999, quantity: 30 },
      { id: 'E-204', name: 'iPad Air 10.9" 64GB', category: 'Electronics', subCategory: 'Accessories', price: 54999, quantity: 25 },
      { id: 'E-205', name: 'Kindle Paperwhite 8GB', category: 'Electronics', subCategory: 'Accessories', price: 12999, quantity: 60 },
    ],
  },
  Clothing: {
    Men: [
      { id: 'C-001', name: "Men's Cotton T-Shirt L", category: 'Clothing', subCategory: 'Men', price: 899, quantity: 120 },
      { id: 'C-002', name: "Men's Denim Jeans 32x32", category: 'Clothing', subCategory: 'Men', price: 1499, quantity: 85 },
      { id: 'C-003', name: "Men's Formal Shirt XL", category: 'Clothing', subCategory: 'Men', price: 1299, quantity: 65 },
      { id: 'C-004', name: "Men's Hoodie M", category: 'Clothing', subCategory: 'Men', price: 999, quantity: 95 },
      { id: 'C-005', name: "Men's Polo Shirt L", category: 'Clothing', subCategory: 'Men', price: 699, quantity: 110 },
    ],
    Women: [
      { id: 'C-101', name: "Women's Summer Dress M", category: 'Clothing', subCategory: 'Women', price: 1899, quantity: 75 },
      { id: 'C-102', name: "Women's Blouse S", category: 'Clothing', subCategory: 'Women', price: 999, quantity: 90 },
      { id: 'C-103', name: "Women's Skinny Jeans 28x30", category: 'Clothing', subCategory: 'Women', price: 1299, quantity: 80 },
      { id: 'C-104', name: "Women's Cardigan M", category: 'Clothing', subCategory: 'Women', price: 1199, quantity: 70 },
      { id: 'C-105', name: "Women's Tank Top S", category: 'Clothing', subCategory: 'Women', price: 499, quantity: 130 },
    ],
    Kids: [
      { id: 'C-201', name: 'Kids T-Shirt Age 6-7', category: 'Clothing', subCategory: 'Kids', price: 399, quantity: 150 },
      { id: 'C-202', name: 'Kids Jeans Age 8-9', category: 'Clothing', subCategory: 'Kids', price: 699, quantity: 120 },
      { id: 'C-203', name: 'Kids Hoodie Age 10-11', category: 'Clothing', subCategory: 'Kids', price: 599, quantity: 100 },
      { id: 'C-204', name: 'Kids Dress Age 5-6', category: 'Clothing', subCategory: 'Kids', price: 799, quantity: 85 },
      { id: 'C-205', name: 'Kids Shorts Age 7-8', category: 'Clothing', subCategory: 'Kids', price: 299, quantity: 180 },
    ],
  },
};
